name: snapshot

# only run if on main branch and there are changes in the components folder
on:
  push:
    branches:
      - develop

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build --filter="./packages/**"

      - name: Publish snapshot
        run: |
          yarn changeset version --snapshot beta
          yarn changeset publish --tag beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
